#!/bin/bash

rm collect/*

./scripts/collect-cpu-usage.sh >collect/cpu-usage &
./scripts/collect-disk-usage.sh >collect/disk-usage &
./scripts/collect-memory-usage.sh >collect/memory-usage &

cd ../../

cat ./assets/monitor/path | xargs -n 2 -P 8 Rscript run.R > ./assets/monitor/collect/procs

ps -ef | grep ./collect | awk '{print $2}' | xargs -n 1 -P 4 kill -9

cd ./assets/monitor/plot

Rscript plot-usages.r ../collect/cpu-usage ../collect/memory-usage ../collect/disk-usage ../collect/procs
